Update custom.yml

diff --git a/.github/workflows/custom.yml b/.github/workflows/custom.yml
--- a/.github/workflows/custom.yml
+++ b/.github/workflows/custom.yml
@@ -27,6 +27,18 @@ jobs:
         run: |
           #flake8 --ignore=E265 .
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+      #- name: Test with pytest
+      #  run: |
+      #    pytest *.py
+          
       - name: Test with pytest
         run: |
-          pytest *.py
+          python -m pytest --verbose --junit-xml=junit.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the preivous step fails
+        with:
+          report_paths: '**/junit.xml'
+          detailed_summary: true
+          include_passed: true
+          
